version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: ozcanaktasweb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ozcanaktasweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ozcanaktasweb_pgdata:/var/lib/postgresql/data

volumes:
  ozcanaktasweb_pgdata:
